Feature/ng 10
pxblue/ionic-design-patterns pull request #16
Opened 2020-10-12 19:29 UTC by emclaug2

#### Changes proposed in this Pull Request:
- Update to angular 10
- http://stackblitz.com/github/pxblue/ionic-design-patterns/tree/feature/ng-10

2020-10-13 11:40 UTC, joebochill reviewed
Changes look reasonable...can't run it on my end just yet.

2020-10-13 11:40 UTC, joebochill commented on angular.json
> +              "./node_modules/@pxblue/angular-themes/theme.scss"
where did the placeholder loading styles go for the loading states example?

2020-10-13 11:40 UTC, joebochill commented on angular.json
> +          "builder": "@angular-devkit/build-angular:tslint",
Is this ts lint stuff supposed to be here if we are using eslint? Is this just boilerplate from angular cli?

2020-10-13 12:15 UTC, emclaug2 commented on angular.json
> +              "./node_modules/@pxblue/angular-themes/theme.scss"
I must have forgotten to migrate these styles over; I bet the angular-design-patterns repo has the same problem.

2020-10-13 12:15 UTC, emclaug2 commented on angular.json
> +          "builder": "@angular-devkit/build-angular:tslint",
Yep you're correct, the lint config is now removed since it's not utilized.

2020-10-14 11:58 UTC, joebochill requested changes
![image](https://user-images.githubusercontent.com/29152776/95985835-1bd3a000-0df3-11eb-99ce-533485b55283.png)

2020-10-15 13:33 UTC, emclaug2 commented
Oops, I forgot to test this out on mobile.  I've added the missing mobile builder to package.json & mobile config to the angular.json file.

This should be working now, tested on android & browser.

2020-10-20 14:12 UTC, joebochill approved these changes

2020-10-20 14:24 UTC, merged