Feature/form validation
pxblue/ionic-design-patterns pull request #24
Opened 2021-04-30 21:10 UTC by andrupu

PXBLUE-1318

Changes proposed in this Pull Request:

- Create the form validation example based on the existing angular design patterns example

2021-05-03 12:15 UTC, emclaug2 commented
To have this tested on a mobile device, you need to add the Form Validation navigation item to the Drawer.  Otherwise can only be tested on a browser which isn't the targeted environment for these ionic apps.

2021-05-03 12:43 UTC, joebochill commented
I'm unable to run the dev branch on a mobile device (at least on my new machine). This was the main reason for the discussion we had last week about the need to re-scaffold this repository. Seems it's gotten a little out of date since we were last in here. I'll check and see if it will run on my old mac.

2021-05-03 12:51 UTC, daileytj commented
I'm not having much luck running this in a browser either.
![Screen Shot 2021-05-03 at 8 49 17 AM](https://user-images.githubusercontent.com/13989985/116877992-b14a4c00-abec-11eb-9a0d-01405ffb5729.png)

2021-05-03 12:55 UTC, joebochill commented
> I'm unable to run the dev branch on a mobile device (at least on my new machine). This was the main reason for the discussion we had last week about the need to re-scaffold this repository. Seems it's gotten a little out of date since we were last in here. I'll check and see if it will run on my old mac.

No dice on the old mac...my ionic environment over there is goofy.

@andrupu if you want to do the rescaffolding as part of this PR, that would be helpful. You would need to generate a new ionic project using the PX Blue CLI and then copy over the 'guts' of the existing project.

```sh
npx -p @pxblue/cli pxb new ionic --name=ionic-design-patterns
```

2021-05-09 21:11 UTC, andrupu commented
I can't seem to create a new ionic scaffold.  It keeps giving me this error:
![image](https://user-images.githubusercontent.com/47467951/117586962-6ac38880-b0e9-11eb-8798-baf01ab25a6a.png)

2021-05-09 22:04 UTC, joebochill commented
I just ran through and created a new project on my mac and it worked as expected. I don't have a PC to test that, but maybe somebody else can confirm that.

Might be related to: 
![image](https://user-images.githubusercontent.com/29152776/117588367-dbba6e80-b0f0-11eb-8b86-6784df0071bf.png)

Make sure you are creating the new project in a new folder, not inside of the ionic-design-patterns repository that you have cloned down.

2021-05-12 22:40 UTC, andrupu commented
I figured it out... I had to set NODE_TLS_REJECT_UNAUTHORIZED=0 due to the Eaton proxy in order to create a new Ionic scaffold.

2021-05-13 11:17 UTC, joebochill commented
> I figured it out... I had to set NODE_TLS_REJECT_UNAUTHORIZED=0 due to the Eaton proxy in order to create a new Ionic scaffold.

Make sure you unset that when you are done :)

2021-05-13 12:41 UTC, emclaug2 commented
It looks like the build is still failing; maybe remove the yarn.lock and create a new one by running `yarn`?

2021-05-13 15:34 UTC, joebochill requested changes

2021-05-13 15:34 UTC, joebochill commented on .browserslistrc
> +# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
We should use our standard browsers list browsers in here (refer to the old file)

2021-05-13 15:34 UTC, joebochill commented on README.md
> +| [Form Validation](https://pxblue.github.io/patterns/lists)                     | Form Fields and various imput fields for validation usage
Use the same description here from the other pattern repos: 'Various types of form validation, such as verifying phone number, email address, character length, and password.'

2021-05-13 15:34 UTC, joebochill commented on .eslintrc.json
> +{
Did you select the PX Blue lint/prettier options when you rescaffolded this? This doesn't look like our typical lint config.

2021-05-13 15:34 UTC, joebochill commented on angular.json
> +            "styles": ["src/theme/variables.scss", "src/global.scss"],
You are missing all of the px blue theming styles in here...are you sure you used our CLI?

2021-05-13 15:34 UTC, joebochill commented on e2e/src/app.e2e-spec.ts
> +    expect(page.getParagraphText()).toContain('Start with Ionic UI Components');
We should have tests in here similar to the tests in the other pattern repositories (see the old file).

2021-05-13 15:34 UTC, joebochill commented on e2e/tsconfig.json
> +    "target": "es2018",
I think we may want to stick with es5 here

2021-05-13 15:34 UTC, joebochill commented on ionic.starter.json
> +{
What is this file (is this a new ionic thing)?

2021-05-13 15:34 UTC, joebochill commented on package.json
> +  "homepage": "https://ionicframework.com/",
This should use the PX Blue author information

2021-05-13 15:34 UTC, joebochill commented on package.json
> +    "lint": "ng lint",
Missing the PX Blue lint and prettier scripts.

2021-05-13 15:34 UTC, joebochill commented on package.json
> +    "@ionic/angular": "^5.5.2",
We're missing all of the PX Blue packages and all of the cordova plugins...I'm thinking you may have scaffolded this with the ionic cli and not the px blue cli...

2021-05-17 15:00 UTC, andrupu commented on ionic.starter.json
> +{
Yes, this is a new generated file in Ionic since the last PXBlue CLI update.

2021-05-17 15:16 UTC, emclaug2 commented
@andrupu Did you push out your latest changes?  I cannot run the angular app, the ionic app doesn't work and the build is still passing, same error as last week.

2021-05-17 19:21 UTC, andrupu commented
> @andrupu Did you push out your latest changes? I cannot run the angular app, the ionic app doesn't build either and the ci/cd pipeline is same error as last week.

Silly me.  I forgot to run yarn.  Also, I found and deleted the redundant browserlist file (browerlistrc) that Circle CI was throwing an error on.

2021-05-18 11:10 UTC, joebochill commented
So I was able to get it to run, but in doing so it shows 60+ file changes.

![image](https://user-images.githubusercontent.com/29152776/118639963-7593b280-b7a6-11eb-801a-2bd7b3a4f991.png)

Most of these are in the resources folder (make sure the gitignore file is updated so that these generated files are not included in the source control).

The config.xml also got overridden with a generic projct name (I suspect you just need to run the project for this file tog et generated and then you can change the strings for project name, description, etc.)

The Form Validation example itself looks off:

![image](https://user-images.githubusercontent.com/29152776/118640043-893f1900-b7a6-11eb-965c-c2963cef6887.png)

It looks like we are closer to getting the re-scaffolding working than the form stuff, so it might behoove us to split this PR (get the final rescaffolding stuff cleaned up and then make a separate PR with the form validation stuff).

The test step is still failing in CI:
![image](https://user-images.githubusercontent.com/29152776/118641201-da034180-b7a7-11eb-967b-9b5d81387e4b.png)

This is something you can check locally by running `yarn test:ci` — it still fails even after adding the missing dependency, so looks like there's still a little work needed there.

2021-05-20 20:03 UTC, joebochill commented
Are we going to close this PR and make a new one with the form validation example now that th scaffold has been updated in the other PR?

2021-05-21 12:47 UTC, andrupu commented
> Are we going to close this PR and make a new one with the form validation example now that th scaffold has been updated in the other PR?

Yes, now that the Scaffold has been merged with the dev branch I am going to close this PR and create a fresh one branched from the updated dev branch.  I will take care of the other branches I created, I just need them to bring the Form Validation changes forward to the new PR.

2021-05-21 15:52 UTC, closed without merging