Form Validation
pxblue/ionic-design-patterns pull request #30
Opened 2021-06-04 15:16 UTC by andrupu

For PXBLUE-1318

Changes proposed in this Pull Request:

- Create the form validation example based on the existing angular design patterns example

2021-06-07 14:17 UTC, emclaug2 commented
Can you make sure these unit tests run locally?
CI is failing on test step: https://app.circleci.com/pipelines/github/pxblue/ionic-design-patterns/128/workflows/aae8c8b1-d931-4d1f-ae5f-8857454d445e/jobs/131

2021-06-10 12:50 UTC, joebochill requested changes
#### Failing Tests in CI
The tests appear to be failing because the new version of karma returns a fail code when we use invalid command line flags:
These are the command line options that are available:
![image](https://user-images.githubusercontent.com/29152776/121527114-118c9480-c9c8-11eb-8f09-da2dc97c8b82.png)

@jeffvg you might need to step in here and help figure out how to do what we need to do with `--code-coverage` and `--no-watch`.

#### Visual Anomolies
When running on a device, the Form Validation page does not look correct. 
- When first navigating to the page, there is a full screen scrim blocking the page. 
- Toolbar has some weird sizing issue, 
- form fields are virtually invisible, 
- etc.:
![image](https://user-images.githubusercontent.com/29152776/121527761-c1620200-c9c8-11eb-91cc-4d5abb15edb2.png)

2021-06-10 12:50 UTC, joebochill commented on angular.json
> +  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
There shouldn't be any changes necessary to angular.json for this. @emclaug2 this file should be covered by our prettier command shouldn't it?

2021-06-10 12:50 UTC, joebochill commented on README.md
> +| [Form Validation](https://pxblue.github.io/patterns/lists)                     | Various types of form validation, such as verifying phone number, email address, character length, and password. usa
Link to the pxblue pattern is pointing to lists instead of form validation.
Missing stackblitz link

2021-06-10 13:00 UTC, jeffvg commented
looks like this branch needs dev merge in. It's missing the reporters in karma config.

reporters: ['progress', 'kjhtml', 'coverage'],

2021-06-14 10:47 UTC, joebochill commented
Looks like you got the tests running now, but 8 of them are failing (for the same reason it looks like). Verified that they are failing locally as well.

2021-06-17 12:51 UTC, joebochill commented
Looking really good. Couple small things:
- Character counter is not working on the character limit example
- I never get a blue checkmark on the 8 character check in the new password field

Otherwise, 👍

2021-06-17 15:29 UTC, emclaug2 commented
@andrupu Delete your local yarn.lock file and run `yarn`.  CircleCI has an issue with your current lock file.

2021-06-17 16:09 UTC, joebochill commented
One last thing...on the new password field it turns blue when not all of the criteria are met:
![image](https://user-images.githubusercontent.com/29152776/122433795-8c275800-cf64-11eb-8672-2a939d760bd5.png)
But it's red if there are fewer than 8 characters entered:
![image](https://user-images.githubusercontent.com/29152776/122433895-a19c8200-cf64-11eb-9052-373d75a2cea9.png)

According to our design pattern (https://pxblue.github.io/patterns/forms#verifying-on-change), this type of input uses the checks to indicate the verification status, so I think we can remove the error state from the input field entirely.

2021-06-18 16:12 UTC, joebochill approved these changes

2021-06-18 16:13 UTC, joebochill commented
Congrats Andrew! Enjoy the green merge button. 🥳

2021-06-18 18:36 UTC, jeffvg commented
I'm having issues with android and ios right now....going to clone fresh to see but this is what I have now...

ionic cordova build android
> ng run app:ionic-cordova-build --platform=android
You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.
[ERROR] An error occurred while running subprocess ng.

2021-06-18 19:07 UTC, jeffvg commented
something must be wrong on my system. The dev branch at least builds for me unlike the feature branch where it fails on build.
But the dev branch error for me is:
```
cordova build android
Unable to load Platform API from /Users/e0458886/pxblue/ionic-design-patterns/platforms/android/cordova/Api.js:
Cannot find module 'properties-parser'
```
- The Api.js file is there but don't see the properties-parser thingy....

```
native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk
[native-run] No hardware devices found, attempting emulator...
[native-run] Selected emulator emulator-5554
[native-run] Error: ENOENT: no such file or directory, open 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'
[ERROR] An error occurred while running subprocess native-run.

        native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug... exited with exit code 1.
```

2021-06-18 19:10 UTC, joebochill commented
Your first issue looks like you have a mix of package-lock and yarn.lock

2021-06-18 21:12 UTC, merged