Add search bar design pattern
pxblue/ionic-design-patterns pull request #5
Opened 2020-09-10 18:14 UTC by daileytj

Fixes PXBLUE-1325.

#### Changes proposed in this Pull Request:
- Add search bar design pattern

2020-09-11 10:55 UTC, joebochill requested changes
Code looks reasonable, but running it on a device has some weird behavior. I'm unable to scroll the list vertically, and I can scroll it horizontally to reveal a search bar:
![image](https://user-images.githubusercontent.com/29152776/92916745-ca06b700-f3fb-11ea-9c9b-d6f1c7045209.png)

2020-09-11 10:55 UTC, joebochill commented on src/app/app-routing.module.ts
> +            // },
No love for the collapsible appbar?

2020-09-11 11:44 UTC, daileytj commented on src/app/app-routing.module.ts
> +            // },
> Code looks reasonable, but running it on a device has some weird behavior. I'm unable to scroll the list vertically, and I can scroll it horizontally to reveal a search bar:
> ![image](https://user-images.githubusercontent.com/29152776/92916745-ca06b700-f3fb-11ea-9c9b-d6f1c7045209.png)

Turns out this is actually a bug with the angular implementation as well. Ill look into trying to fix this.

2020-09-11 16:10 UTC, joebochill commented on src/app/app-routing.module.ts
> +            // },
I logged an issue for the lists not scrolling vertically: https://github.com/pxblue/ionic-design-patterns/issues/6

2020-09-14 17:48 UTC, emclaug2 commented
The searchbar is working fine for me now, but when I scroll down the appbar isn't pinned to the top of the screen.

2020-09-14 18:25 UTC, joebochill commented
> The searchbar is working fine for me now, but when I scroll down the appbar isn't pinned to the top of the screen.

We've got a followup issue to deal with the wonky scrolling: #6

2020-09-14 18:25 UTC, joebochill approved these changes

2020-09-15 10:02 UTC, merged